services:
  renamer:
    build:
      context: ../services/video-processing/renamer
    container_name: renamer-service
    restart: unless-stopped
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    ports:
      - "8010:8000"
    volumes:
      - ../services/video-processing/renamer/src:/app/src
    entrypoint: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - vsl-main
