services:
  auth:
    build:
      context: ../services/auth
    container_name: auth-service
    restart: unless-stopped
    environment:
      SECRET_KEY: ${AUTH_SECRET_KEY}

      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_HOST: auth-db
      POSTGRES_PORT: 5432

      ISSUER_NAME: auth
    ports:
      - "8000:8000"
    volumes:
      - ../services/auth/src:/app/src
      - ../services/auth/permissions.yaml:/app/permissions.yaml:ro
      - ../services/auth/manage.py:/app/manage.py:ro
    entrypoint: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    networks:
      - vsl-main

  auth-db:
    image: postgres:17
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ../data/auth/postgresql/data:/var/lib/postgresql/data
    networks:
      - vsl-main

